/**
 * ai.logger.ts
 *  AI-specific log events
 */
import { logError, logInfo, logWarn } from "./logger.js";


//on agent start (user question)
export function traceAgentStart(input: AgentTraceStart): void {
    logInfo("agent.request.started", {
      question: input.question,
      propertyName: input.propertyName
    });
}
export interface AgentTraceStart {
  question: string;
  propertyName: string;
}





export function traceCacheHit(question: string) {
  logInfo("cache.hit", { question });
}
export function traceCacheMiss(question: string) {
  logInfo("cache.miss", { question });
}
export function traceCacheSet(question: string) {
  logInfo("cache.set", { question });
}


//on retrieval completed (keyword or embedding search on property file)
export function traceAgentRetrieval(input: AgentTraceRetrieval): void {
    logInfo("agent.retrieval.completed", {
      question: input.question,
      retrievalMethod: input.retrievalMethod,
      topScore: input.topScore,
      citations: input.citations,
      retrievedChunkCount: input.retrievedChunkCount
    });
  }export interface AgentTraceRetrieval {
  question: string;
  retrievalMethod?: string;
  topScore?: number;
  citations: string[];
  retrievedChunkCount: number;
}




//on agent finish (answer generated by LLM)
export function traceAgentFinish(input: AgentTraceFinish): void {
    logInfo("agent.request.completed", {
      question: input.question,
      grounded: input.grounded,
      citations: input.citations,
      answerLength: input.answerLength,
      durationMs: input.durationMs
    });
  }
export interface AgentTraceFinish {
  question: string;
  grounded: boolean;
  citations: string[];
  answerLength: number;
  durationMs: number;
}





export function traceAgentFailure(input: AgentTraceFailure): void {
    logError("agent.request.failed", {
      question: input.question,
      durationMs: input.durationMs,
      error:
        input.error instanceof Error
          ? {
              name: input.error.name,
              message: input.error.message,
              stack: input.error.stack
            }
          : input.error
    });
  }
export interface AgentTraceFailure {
  question: string;
  durationMs?: number;
  error: unknown;
}




export function traceAgentNoContext(question: string): void {
  logWarn("agent.retrieval.empty: couldnt find relevant information in the knowledge file", {
    question
  });
}

